---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: sb-crud-deployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: contactbackend
 template:
  metadata:
   name: contactbackend
   labels:
     app: contactbackend
  spec:
    containers:
    - name: sb-crud-container
      image: contact_backend_app
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: sb-crud-svc
spec:
  type: NodePort
  selector:
   app: contactbackend
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30001